## eigendecomposition exercise

In [109]:
# import numpy
import numpy as np
import math

**Task:** Create a matrix (2x2) called matrix 'A'.


In [110]:
A = np.array([(5,6),(7,9)])

In [111]:
A.shape[0]

2

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [112]:
def shape_2x2(matrix):
# """
# Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

# PARAMS:
#     matrix (numpy.ndarray) - matrix to check
# RETURN:
#     True (bool) - if matrix has shape 2x2
#     False (bool) - if matrix has not shape 2x2

# """
    try:
        if (matrix.shape[0] == 2) & (matrix.shape[1] == 2):
            return True
        else:
            return(False)
    except:
        return(False)

In [35]:
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [113]:
def determinant_2x2(matrix):
# """
# Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

# PARAMS:
#     matrix (numpy.ndarray) - matrix to compute determinant
# RETURN:
#     det (float) - matrix determinant

# """
    if shape_2x2(matrix):
        return( matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0])
    else:
        return('Need a square 2 x 2 for this function to work')


In [114]:
determinant_2x2(A)

3

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [115]:
determinant_2x2(A)

3

In [116]:
np.linalg.det(A)

3.000000000000001

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [117]:
eigenvals, V = np.linalg.eig(A)

**Task:** Print the eigenvalues.

In [118]:
eigenvals

array([ 0.21767002, 13.78232998])

**Task:** Print  the eigenvectors.

In [119]:
V

array([[-0.78199094, -0.56410982],
       [ 0.62328979, -0.82569977]])

In [108]:
matrix = A
I = np.eye(2)
trace = matrix[0][0] + matrix[1][1] # sum of diagonal of matrix
p = determinant_2x2(matrix - np.inner(trace, I))#trace.np.dot(I))

#     Quadratic Equation to find eigenvalues
lambda1 = (trace - math.sqrt(trace**2 - 4*determinant_2x2(matrix))) /2
lambda2 = (trace + math.sqrt(trace**2 - 4*determinant_2x2(matrix))) /2

result_l2 = matrix-I *lambda2

# eq1 = resultl2[0][0]*x1 +resultl2[0][1]*x2
# eq2 = resultl2[1][0]*x1 +resultl2[1][1]*x2

A = np.array([resultl2[0][0], resultl2[0][1]], [resultl2[1][0], resultl2[1][1]])
B = np.array([0, 0])
X = np.linalg.solve(A,B)
X
# 20x + 10y = 350
# 17x + 22y = 500
# A = np.array([[20, 10], [17, 22]])
# B = np.array([350, 500])
# X = np.linalg.solve(A,B)


NameError: name 'resultl2' is not defined

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [145]:
def eig_2x2(matrix):
# """
# Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

# PARAMS:
#     matrix (numpy.ndarray) - matrix to perform decomposition
# RETURN:
#     eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

# """
    I = np.eye(2)
    trace = matrix[0][0] + matrix[1][1] # sum of diagonal of matrix
#     p = determinant_2x2(matrix - np.inner(trace, I))#trace.np.dot(I))
    
#     Quadratic Equation to find eigenvalues
    lambda1 = (trace - math.sqrt(trace**2 - 4*determinant_2x2(matrix))) /2
    lambda2 = (trace + math.sqrt(trace**2 - 4*determinant_2x2(matrix))) /2
    
    resultl2 = matrix-I *lambda2
# # Find eigenvectors
# #     solve lambda *matrix *v = 0
    A = np.array([[resultl2[0][0], resultl2[0][1]], [resultl2[1][0], resultl2[1][1]]])
    B = np.array([0, 0])
    X = np.linalg.solve(A,B)
    print('X')
    print(X)


    return np.array([lambda1, lambda2])  

In [138]:
def eig_2x2(matrix):
#     if type(determinant_2x2(matrix)) == float:
    det = determinant_2x2(matrix)
    trace = matrix[0,0] + matrix[1,1]
    eigenvalues = np.array([((trace - np.sqrt(trace**2 - 4*det))/2),
               ((trace + np.sqrt(trace**2 - 4*det))/2)])
    eigenvectors = []
    for eig in eigenvalues:
        matrix_minus_eig = matrix - eig*np.eye(matrix.shape[0])
        eigenvector = np.array([-matrix_minus_eig[0,1], matrix_minus_eig[0,0]])
        eigenvector_norm = eigenvector/np.linalg.norm(eigenvector)
        eigenvectors.append(eigenvector_norm)
    eigenvectors = np.array(eigenvectors).T
    return eigenvalues, eigenvectors
#     else:
#         print('Error, not a 2x2 matrix')

In [136]:
eig_2x2(A)

(array([ 0.21767002, 13.78232998]),
 array([[-0.78199094, -0.56410982],
        [ 0.62328979, -0.82569977]]))

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [139]:
eig_2x2(A)

(array([ 0.21767002, 13.78232998]),
 array([[-0.78199094, -0.56410982],
        [ 0.62328979, -0.82569977]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [140]:
eigenvals, V = np.linalg.eig(A)

In [67]:
eigenvals

array([ 0.21767002, 13.78232998])

In [77]:
V

array([[-0.78199094, -0.56410982],
       [ 0.62328979, -0.82569977]])

In [ ]:
np.allclose(eigenvals, 

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [141]:
B = np.array([[0,1],[-1,0]])

In [142]:
B

array([[ 0,  1],
       [-1,  0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [146]:
eig_2x2(B)

ValueError: math domain error

In [144]:
determinant_2x2(B)

1

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [ ]:
# one may be scaled??